[project]
name = "postschedulerbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.18.0",
    "aiogram-fsm-sqlitestorage>=1.0.0",
    "apscheduler>=3.11.0",
    "piccolo[sqlite]>=1.24.0",
    "pydantic-settings>=2.8.1",
]
